### ISSUE TITLE
def stream_user(self, listener, async=False): SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hanscees** [halcy/Mastodon.py#247]
Hi, I am sure I am doing something stupid, but no idea what. 

initiating like htis:
`#!/usr/bin/python3
import requests, datetime
import os, re
from mastodon import Mastodon`

I get the error
`from mastodon import Mastodon
  File "/home/hanscees/miniconda3/envs/mastodon2022/lib/python3.10/site-packages/mastodon/__init__.py", line 1, in <module>
    from mastodon.Mastodon import Mastodon
  File "/home/hanscees/miniconda3/envs/mastodon2022/lib/python3.10/site-packages/mastodon/Mastodon.py", line 1384
    def stream_user(self, listener, async=False):
                                    ^^^^^
SyntaxError: invalid syntax
`

Please help

**Comment by codl** [comment]
Which version of the library are you using? This looks like an old issue (#120) with Python ≥ 3.7, which was fixed in Mastodon.py 1.3.0 and higher.

**Comment by hanscees** [comment]
I use anaconda, and apparently that site thinks the latest version is 1.2.2
see
https://anaconda.org/conda-forge/mastodon.py/files

So yes I have an ancient version.. 

Is there a way to ping that conda stuff so they update?

**Comment by codl** [comment]
I see you've opened an issue with conda-forge, linking for reference: https://github.com/conda-forge/mastodon.py-feedstock/issues/14. Not sure what's going on there, looks like there are several automated pull requests adding newer versions of Mastodon.py that have been collecting dust for years...

I'm not too familiar with anaconda/conda but, until the conda-forge package is updated, I believe you should be able to [run pip inside your conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) to install the latest version of Mastodon.py from PyPI.

**Comment by hanscees** [comment]
Collecting dust for 4,5 years.
I have after a lot of fiddling been able to run pip inside a conda environment and install a modern version.
But now Python still doesn't see the package. 
I will delve in more tonight. 

It's great to see mastodon growing like a teenager this week after the Elon singularity

**Comment by halcy** [comment]
I will leave this open as a reminder to figure out if I can update the conda package somehow

**Comment by jsta** [comment]
@halcy You can open a "bot command" issue in the feedstock repo (https://github.com/conda-forge/mastodon.py-feedstock/issues/new/choose) with the following text to be added as maintainer (`@conda-forge-admin, please add user @halcy`)

**Comment by jsta** [comment]
I made myself a maintainer. The issue blocking update of the conda package is that there is no `http-ece` (`http_ece`) package on conda-forge.

**Comment by hanscees** [comment]
The things you learn about this world while troubleshooting are always tremendous. 
Http-ece lives here apparantly: https://pypi.org/project/http-ece/

**Comment by jsta** [comment]
Yep, but it has to live on conda not pypi for the mastdon.py conda build to work. I've put http-ece on conda-forge, made myself a maintainer of mastodon.py on conda-forge, and update the build to the latest version 1.6.3.

Could you see if the conda build works for you @hanscees ?

https://anaconda.org/conda-forge/mastodon.py

**Comment by hanscees** [comment]
Yes, but not today, this week yes

**Comment by jsta** [comment]
I think this issue can be closed. I've verified that the conda-forge package version (1.6.3) works for me.

**Comment by halcy** [comment]
Guess someone started updating it. That's neat. Thanks for letting me know.
